name: flipper_socials
description: An app build with the stacked framework

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  stacked: ^3.4.1+1
  stacked_services: ^1.0.4
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.0

  google_fonts: ^6.1.0
  flipper_services: ^1.0.0
  flipper_models: ^0.0.1-dev.7
  flipper_routing: ^0.0.1-dev.3

  fluentui_system_icons: ^1.1.203
  animated_icon_button: ^1.0.2
  pip_view: ^0.9.7
  getwidget: ^3.0.1
  timeago: ^3.4.0
  fast_cached_network_image: ^1.1.1
  # custom_floating_action_button: ^0.0.3
  flutter_chat_ui: ^1.6.8
  #TODO: added flipper_dashboard here only becase we need customAppBar
  # may be it is time to create utils package and move everything shareble 
  # in all packages or use flipper_ui package
  flipper_dashboard: ^0.0.1-dev.5
  url_launcher: ^6.1.11
dependency_overrides:
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  stacked_generator: 1.0.0
  mockito: ^5.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - google_fonts/
