name: customappbar
description: custom app bar for flipper app.
version: 0.0.1
homepage: "https://yegobox.com"

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  apptheme: ^0.0.1
  flipper_ui: ^0.0.1
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
