name: customappbar
description: custom app bar for flipper app.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  apptheme:
    path: ../apptheme

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
