name: customappbar
description: custom app bar for flipper app.
version: 0.0.3
homepage: "https://yegobox.com"

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  apptheme: ^0.0.1
  flipper_ui: ^0.0.2
  google_fonts: ^0.3.10
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  #  flutter pub publish --dry-run
  # flutter pub publish