name: flipper_localize
description: Flipper localization
version: 1.0.0-dev
repository: https://github.com/yegobox/packages

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

flutter:
  generate: true
