name: flipper_localize
description: Flipper localization
version: 1.0.0-dev
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_ui_auth: ^1.14.0

  firebase_ui_localizations: ^1.9.0
