name: demo_ui_components
description: Module to contain commonly shared ui components in example modules
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.4 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.16.0
  wolt_responsive_layout_grid: ^0.0.3
  google_fonts: ^6.1.0
  wolt_modal_sheet: ^0.11.0

dev_dependencies:
  flutter_lints: ^3.0.1
  test: 

flutter:
  uses-material-design: true
