name: flipper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 99.99.99+99

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  country_code_picker: ^2.0.1
  flutter_country_picker: ^0.1.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  universal_platform: ^1.0.0+1
  animations: ^2.0.0
  flutter_localized_locales: ^2.0.1
  # sized_context: ^0.2.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  injectable: ^1.2.0
  http: ^0.13.0
  get_it: ^6.0.0
 
 
  firebase_messaging: ^10.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.3.0
  stacked_firebase_auth: ^0.2.2+1
  cloud_firestore: ^1.0.1
  camera: ^0.8.0
  awesome_notifications: ^0.0.6+7
  # geolocator:
  location: ^4.1.1
  # permission_handler:
  built_value:
  built_collection:
  jiffy: 
  expandable: ^5.0.1
  timezone: ^0.7.0
  cupertino_icons:
  get_storage: ^2.0.2
  country_picker:
 
  rxdart:
 
  firebase_crashlytics: 
  logger:
  async:
  stacked: ^2.1.4
  stacked_hooks:
  stacked_services: 
  cached_network_image: ^3.0.0
  flutter_dotenv: ^5.0.0
  mailer:
  connectivity:
 
  get: 
  flutter_slidable: ^0.6.0
  in_app_review: ^2.0.2
  timeago:
  cron:
  number_display: ^3.0.0
  # esc_pos_utils: not available
  flutter_uploader: 3.0.0-beta.2
  # I do not think bitsdojo_window is needed for now but it might be in future
  # bitsdojo_window: 
  observable_ish:
  qr_flutter: ^4.0.0
  adaptive_breakpoints: ^0.0.4
  
# TODO: start moving some packages into differed dependencies see gallery for case study!
# custom packages locally built
  flipper_dashboard:
    path: 'packages/flipper_dashboard'
  flipper_login:
    path: 'packages/flipper_login'
  flipper_models:
    path: 'packages/flipper_models'
  flipper_services:
    path: 'packages/flipper_services'
  flutter_money_formatter:
    path: 'packages/flutter_money_formatter' #to be replace when PR is merged
  loading: 
    path: 'packages/loading'
  flipper_ui:
    path: 'packages/flipper_ui'
  chat:
    path: 'packages/chat'
  flipper_routing:
    path: 'packages/flipper_routing'
  flipper_chat:
    path: 'packages/flipper_chat'
      
  google_fonts:
  font_awesome_flutter: ^9.0.0
  flutter_text_drawable: ^1.0.0
  moor_flutter: ^4.0.0
  firebase_dynamic_links: ^2.0.1
  firebase_analytics: ^8.0.3
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils_plus: ^2.0.1+3
  printing: ^5.2.1
  couchbase_lite_dart: ^0.5.0-nullsafety.3
  
  flutter_native_splash: ^1.1.8+4
  stomp_dart_client: ^0.4.1
  hive: ^2.0.4
  flutter_luban: ^0.1.13
  image: ^3.0.2
  msix: ^2.0.0
  image_picker: ^0.8.0+4
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
      ref: master
  intl: ^0.17.0
  provider: ^5.0.0
  rounded_loading_button: ^2.0.4
  hive_flutter: ^1.0.0
  path_provider: ^2.0.2
  objectbox: ^1.1.1
  objectbox_flutter_libs: any
  dio: ^4.0.0
  # freezed: ^0.14.2
  firebase_remote_config: ^0.10.0+2
  settings_ui: ^1.0.0
  # flutter_datetime_picker: ^1.5.1 (this had a warning! need to check in future if thre is update but for now use it directly from git)
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  open_file: ^3.2.1
  firebase_performance: "^0.7.0+5"
  share_plus: ^2.1.4
  # rubber: ^1.0.0
  overlay_support: ^1.2.1
  flutter_screenutil: ^5.0.0+2
  flutter_local_notifications: ^6.0.0
  # flutter_chat_ui: ^1.1.3
  # flutter_chat_ui: 
  # cbl: ^0.6.0
  # cbl_flutter: 
  # TODO: implement feedback flow later created aount in wiredash using yegobox@gmail.com google login
  # wiredash: ^0.6.0
  
  # objectbox: ^1.0.0
  # objectbox_flutter_libs: any
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:
  stacked_generator:
  mockito: 5.0.8
  test: ^1.5.3
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.0
  objectbox_generator: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
# msix_config:
#   display_name: Flipper
#   publisher_display_name: Yegobox
#   identity_name: Yegobox.Flipper
#   msix_version: 1.0.0.2
#   certificate_path: ./certs/CERTIFICATE.pfx
#   certificate_password: "::flipper::"
#   publisher: E="yegobox@gmail.com" CN="yegobox.com" O="Yegobox Ltd" L=Kigali S=G C=RW
#   # logo_path: C:\<PathToIcon>\<Logo.png>
#   # start_menu_icon_path: C:\<PathToIcon>\<Icon.png>
#   # tile_icon_path: C:\<PathToIcon>\<Icon.png>
#   # vs_generated_images_folder_path: C:\<PathToFolder>\icons
#   # icons_background_color: transparent
#   architecture: x64
#   capabilities: 'internetClient,location,microphone,webcam'
#   store: true
  # ::flipper::
  # https://www.codestories.gr/index.php/2019/03/17/generate-a-pfx-certificate-using-the-windows-certificate-store/
  # https://www.codestories.gr/index.php/2019/03/22/generate-a-pfx-certificate-using-openssl/
  # https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe
  # https://docs.microsoft.com/en-us/windows/msix/package/create-app-package-with-makeappx-tool
  # https://github.com/YehudaKremer/msix/issues/19
  # Final (https://sahajrana.medium.com/how-to-generate-a-pfx-certificate-for-flutter-windows-msix-lib-a860cdcebb8)

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - vendor/
  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
  generate: true
  # https://flutter.dev/docs/perf/deferred-components (getting ready with way forward.)
  # deferred-components:
  # flutter run
  # flutter create --template=package hello
  # ./flutterw packages pub run build_runner build --delete-conflicting-outputs

  # openssl genrsa -out windows.key 2048
  # openssl req -new -key windows.key -out csr.csr
  # openssl x509 -in csr.csr -out crt.crt -req -signkey windows.key -days 365
  # openssl pkcs12 -export -out CERTIFICATE.pfx -inkey windows.key -in crt.crt
  # update version.
  # update version.
  # update version.
