name: flipper
description: flipper business app.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.78


environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.0.2
  flutter_svg: ^0.18.0 

 
  geolocator: ^5.3.0
  permission_handler: ^4.3.0
  flutter_circular_chart: ^0.1.0
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  flutter_masked_text: ^0.8.0
  built_value: ^7.0.9
  image_picker: ^0.6.4
  built_collection: ^4.3.2
  flutter_date_pickers: ^0.0.6
  flutter_material_color_picker: ^0.0.5
  flutter_image_compress: ^0.6.5+1
  flutter_platform_widgets: 0.20.3-beta.1
  uuid: 2.0.4
  timezone: ^0.5.6
  flutter_barcode_scanner: 
  moor: ^3.0.0
  sqlite3_flutter_libs:
  sqflite: ^1.1.7 
  #  built_collection: ^4.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
 
  #local package
  google_fonts:  ^1.1.0
  customappbar: ^1.0.0
  flipper_ui: ^1.0.0
  apptheme: ^1.0.0
  rubber: ^0.4.0
  shared_preferences: 0.5.2
  # background_fetch: 0.6.0
  # flutter_uploader: ^1.2.0 
  fluttercouch:
   git:
     url: git://github.com/oltrenuovefrontiere/fluttercouch.git
     ref: master
  # Firebase dependencies
  # social sign in
  # google_sign_in: "^4.5.1"
  # firebase_auth: ^0.18.0
  # end social signin
  firebase_core: ^0.5.0
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.11
  # cloud_firestore: ^0.14.0
  # end of firebase dependency 
  camera: 0.5.8+2
  flipper_login:
    path:
      './packages/flipper_login'
  scoped_model:
  sms_autofill: ^1.2.3
#  wifi_info_plugin: ^1.0.6
#  flutter_bluetooth_serial: ^0.2.2
#  flutter_scan_bluetooth: ^1.1.0
  fl_chart:
  flutter_uploader:
  # couchbase_lite:
  #   git:
  #     url: https://github.com/SaltechSystems/couchbase_lite.git
  #     ref: master

dev_dependencies:
  moor_generator: ^3.0.0
  flutter_test:
    sdk: flutter
  analyzer: '0.39.14'
  build_runner: ^1.10.1
  auto_route_generator: ^0.3.2
  built_value_generator:
  test: ^1.6.1
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.4
  

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_foreground: 'assets/icon/icon.png'
  adaptive_icon_background: '#FFFFFF'

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/graphics/
    - assets/card_provider/
    - assets/graphics/drawer/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
flutter_intl:
  enabled: true

# 1.5.33
#  flutter packages pub run build_runner watch --delete-conflicting-outputs  --enable-experiment=non-nullable
#  rw.flipper
# app bundle
# flutter build appbundle --build-name=1.5.78  --build-number=1578
# app apk
# flutter build apk --build-name=1.5.78  --build-number=1578
# Db on device for debugging purpose: This PC\Pixel\Internal shared storage\Android\data\rw.flipper\files\database-development

# icon
# flutter pub run flutter_launcher_icons:main

