name: flipper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 99.99.99+99

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  country_code_picker: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  universal_platform: ^1.0.0+1
  animations: ^2.0.0
  flutter_localized_locales: ^2.0.1
  # sized_context: ^0.2.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  injectable: ^1.2.0
  http: 0.13.4
  firebase_auth: ^3.1.5
  firebase_auth_desktop: ^0.1.1-dev.0
  firebase_core: 1.10.0
  firebase_core_desktop: ^0.1.1-dev.0
  stacked_firebase_auth: ^0.2.10
  cloud_firestore: 3.1.0
  camera: 0.9.4+5
  awesome_notifications: ^0.0.6+10
  location: ^4.3.0
  # permission_handler:
  built_value:
  built_collection:
  jiffy:
  expandable: ^5.0.1
  timezone: ^0.7.0
  cupertino_icons:
  get_storage: ^2.0.2
  country_picker:

  rxdart:

  firebase_crashlytics:
  logger:
  async:
  stacked: ^2.2.5
  get_it: #to match with the stacked version I leave it empty
  stacked_hooks:
  stacked_services:
  stacked_themes:
  cached_network_image: ^3.1.0+1
  flutter_dotenv: ^5.0.0
  mailer:

  get:
  flutter_slidable: ^0.6.0
  in_app_review: ^2.0.2
  timeago:
  cron:
  number_display: ^3.0.0
  # esc_pos_utils: not available
  flutter_uploader: 3.0.0-beta.2
  # I do not think bitsdojo_window is needed for now but it might be in future
  # bitsdojo_window:
  observable_ish:
  qr_flutter: ^4.0.0
  adaptive_breakpoints: ^0.0.4

  # TODO: start moving some packages into differed dependencies see gallery for case study!
  # custom packages locally built
  flutter_country_picker:
    path: "open-sources/flutter_country_picker"
  flipper_dashboard:
    path: "packages/flipper_dashboard"
  flipper_login:
    path: "packages/flipper_login"
  flipper_models:
    path: "packages/flipper_models"
  flipper_view_models:
    path: "packages/flipper_view_models"
  flipper_services:
    path: "packages/flipper_services"
  money_formatter:
    path: "open-sources/money_formatter"
  loading:
    path: "packages/loading"
  flipper_ui:
    path: "packages/flipper_ui"
  flipper_routing:
    path: "packages/flipper_routing"
  flipper_chat:
    path: "packages/flipper_chat"
  flipper_map:
    path: "packages/flipper_map"
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
      ref: master
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  animated_toggle_switch:
    path: "open-sources/animated_toggle_switch"
  flutter_chat_ui:
    path: "open-sources/flutter_chat_ui"
  # flutter_chat_ui: ^1.4.1
  flutter_firebase_chat_core:
    path: "open-sources/flutter_firebase_chat_core"
  firestore_cache:
    path: "open-sources/firestore_cache"
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.0.0
  flutter_text_drawable: ^1.0.0
  moor_flutter: ^4.0.0
  firebase_dynamic_links: ^2.0.1
  firebase_analytics: ^8.0.3

  # flutter_blue: ^0.8.0 //I do not know how this can be used.
  esc_pos_utils_plus: ^2.0.1+3
  printing: ^5.2.1
  couchbase_lite_dart: ^0.5.0-nullsafety.3

  flutter_native_splash: ^1.1.8+4
  stomp_dart_client: ^0.4.3
  hive: ^2.0.4
  flutter_luban: ^0.1.13
  image: ^3.0.2
  # https://www.advancedinstaller.com/msix-publish-microsoft-store.html
  image_picker: ^0.8.0+4

  intl: ^0.17.0
  provider: ^5.0.0
  rounded_loading_button: ^2.0.4
  hive_flutter: ^1.0.0
  path_provider: ^2.0.7
  objectbox: ^1.3.0
  objectbox_sync_flutter_libs: any
  dio: ^4.0.0
  file_picker: ^4.2.7
  firebase_remote_config: ^0.10.0+2
  # settings_ui: ^1.0.0

  open_file: ^3.2.1
  firebase_performance: "^0.7.1+1"
  share_plus: ^2.1.4

  overlay_support: ^1.2.1
  flutter_screenutil: ^5.0.0+2
  flutter_local_notifications: ^6.0.0

  qr_code_scanner: ^0.5.2
  feather_icons: ^1.1.0-nullsafety.0
  ionicons: ^0.1.2
  ant_icons: ^2.0.0-nullsafety.0
  fl_chart: ^0.40.0
  azlistview: ^2.0.0-nullsafety.0
  common_utils: ^2.0.2
  # remove after flutter_chat is updated
  # lpinyin: ^2.0.3
  # github_language_colors:
  #   git:
  #     url: git://github.com/Sky24n/github_language_colors.git
  random_string:
  upgrader: ^3.5.1
  flutter_svg: ^0.22.0
  # jovial_svg: ^1.0.6
  internet_connection_checker: ^0.0.1+2
  connectivity_plus: "^1.1.0"

  firebase_storage: ^10.0.3
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  flutter_secure_storage: ^4.2.1
  url_launcher: ^6.0.12
  google_sign_in: ^5.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.3
  nb_utils: ^4.4.8
  fluent_ui: ^3.2.0
  system_theme: ^1.0.1
  flutter_acrylic: ^0.0.3
  flutter_form_bloc: ^0.20.6
  flutter_inappwebview: ^5.3.2
  nfc_manager: ^3.1.0
  google_maps_flutter: ^2.0.11
  flutter_polyline_points: ^1.0.0
  sentry_flutter: ^6.1.2
  geolocator: ^7.7.1
  geocode: ^1.0.1
  flex_color_picker: ^2.2.0
  flex_color_scheme: ^4.1.1
  flutter_staggered_grid_view: ^0.4.1

  # Material Design Icons, community designed. Used for nicer
  # icons to the Platform selection popup menu.
  material_design_icons_flutter: ^5.0.6295
  firebase_messaging: ^11.2.3
  flutter_settings_ui: ^2.0.1
  auto_size_text: ^3.0.0

  bluetooth_thermal_printer: ^0.0.6
  # FIXME:switch to the bellow bluethooth package
  # blue_thermal_printer: ^1.1.8
  # ffi: 1.0.0
  # flutter_qr_reader: 1.0.5
  # end remove
  # flutter_chat_ui:
  # cbl: ^0.6.0
  # cbl_flutter:
  # TODO: implement feedback flow later created aount in wiredash using yegobox@gmail.com google login
  # wiredash: ^0.6.0
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:
  stacked_generator:
  mockito: 5.0.8
  test: ^1.5.3
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.0
  objectbox_generator: any
  matcher: ^0.12.10
  flutter_lints:
  msix: ^2.6.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
# While developing comment the following lines
# msix_config:
#   display_name: Flipper
#   publisher_display_name: Yegobox
#   identity_name: Yegobox.Flipper
#   msix_version: 1.0.0.4
#   # cert will not be needed when deployed on microsoft.
#   certificate_path: ./certs/CERTIFICATE.pfx
#   certificate_password: "::flipper::"
#   # TODO: when ready for prod see publisher here https://partner.microsoft.com/en-us/dashboard > Product > Product identity > Package/Identity/Publisher
#   publisher: CN=My Company, O=My Company, L=Berlin, S=Berlin, C=DE
#   logo_path: .\assets\icon\icon.png
#   start_menu_icon_path: .\assets\icon\icon.png
#   tile_icon_path: .\assets\icon\icon.png
#   icons_background_color: transparent
#   architecture: x64
#   capabilities: "internetClient,location,microphone,webcam"
#   store: true
# ::flipper::
# https://www.codestories.gr/index.php/2019/03/17/generate-a-pfx-certificate-using-the-windows-certificate-store/
# https://www.codestories.gr/index.php/2019/03/22/generate-a-pfx-certificate-using-openssl/
# https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe
# https://docs.microsoft.com/en-us/windows/msix/package/create-app-package-with-makeappx-tool
# https://github.com/YehudaKremer/msix/issues/19
# Final (https://sahajrana.medium.com/how-to-generate-a-pfx-certificate-for-flutter-windows-msix-lib-a860cdcebb8)

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - packages/flipper/assets/fliper-logo.png
    - assets/
    - assets/images/
    - assets/icons/
    - vendor/
  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
  generate: true
  # https://flutter.dev/docs/perf/deferred-components (getting ready with way forward.)
  # deferred-components:
  # flutter run
  # flutter create --template=package hello
  # ./flutterw packages pub run build_runner build --delete-conflicting-outputs
  # openssl genrsa -out windows.key 2048
  # openssl req -new -key windows.key -out csr.csr
  # openssl x509 -in csr.csr -out crt.crt -req -signkey windows.key -days 365
  # openssl pkcs12 -export -out CERTIFICATE.pfx -inkey windows.key -in crt.crt
  # update version.
  # update version.
  # update version.
  # update version.
  # update version.
  # update version.
