name: flipper
description: flipper business app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.32

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.11
  flutter_svg: ^0.17.2
  #for sending emails, sync etc...
  # cron: ^0.2.2  //I replaced it with background_fetch I think it is better.
  background_fetch: ^0.5.5
  flutter_uploader: ^1.2.0
  fluttercouch:
    git:
      url: https://github.com/yegobox/fluttercouch.git
      ref: master
  scoped_model: ^1.0.1

  strings: ^0.1.2
  flutter_secure_storage: ^3.3.1+1
  auto_route: ^0.3.1
  charts_flutter: ^0.9.0
  fl_chart: ^0.8.7
  # Firebase dependencies
  firebase_core: ^0.4.4+2
  flutter_webview_plugin: ^0.3.10+1
  firebase_messaging: ^6.0.12
  firebase_crashlytics: ^0.1.3+3
  http: ^0.12.0+4
  # moor: 
  # moor_ffi: ^0.4.0
  # new moor that has table listners that we need. 
  path_provider: 1.6.11
  path: ^1.6.4
  json_annotation: ^3.0.1
  cached_network_image: 1.1.3
  geolocator: ^5.3.0
  query_params: ^0.6.1
  random_string: ^2.0.1
  permission_handler: ^4.3.0
  flutter_circular_chart: ^0.1.0
  fluttertoast: ^3.1.3
  #  pusher_websocket_flutter: ^0.1.1
  #   Redux dependencies
  redux: ^4.0.0
  camera: 0.5.8+2
  flutter_redux: ^0.6.0
  flutter_masked_text: ^0.8.0
  built_value: ^7.0.9
  image_picker: ^0.6.4
  # transparent_image: ^1.0.0
  firebase_analytics: ^5.0.11
  built_collection: ^4.3.2
  flutter_date_pickers: ^0.0.6
  flutter_material_color_picker: ^0.0.5
  # We fixed a bug in the plugin
  #  media_picker_builder:
  #    git:
  #      url: git://github.com/janoodleFTW/media_picker_builder.git
  #      ref: master
  # abandoned this flutter_native_image now use flutter_image_compress
  #  flutter_native_image:
  #    git:
  #      url: https://github.com/btastic/flutter_native_image.git
  #      ref: fix/ios_compression
  flutter_image_compress: ^0.6.5+1
 
  #  pinch_zoom_image: ^0.2.5
  # TODO(richard): the flutter_platform_widgets: 0.20.3-beta.1 is the only version mathing beta channel please do not change
  flutter_platform_widgets: 0.20.3-beta.1
  flutter_linkify: ^3.1.0
  uuid: 2.0.4
  timezone: ^0.5.6
  
  #  built_collection: ^4.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
dependency_overrides:
  moor:
    git:
      url: https://github.com/simolus3/moor.git
      ref: beta
      path: moor
  moor_ffi:
    git:
      url: https://github.com/simolus3/moor.git
      ref: beta
      path: moor_ffi
  moor_generator:
    git:
      url: https://github.com/simolus3/moor.git
      ref: beta
      path: moor_generator
  sqlparser:
    git:
      url: https://github.com/simolus3/moor.git
      ref: beta
      path: sqlparser

  #local package
  google_fonts:  ^1.1.0
  customappbar: ^1.0.0
  flipper_ui: ^1.0.0
  apptheme: ^1.0.0
  subscription:
    path: ./packages/subscription

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^1.7.4
  auto_route_generator: ^0.3.2
  built_value_generator: ^7.0.9
  # moor_generator: ^2.4.0
  # moor_generator:
  #   git:
  #     url: https://github.com/simolus3/moor.git
  #     ref: beta
  #     path: moor_generator

  
#  json_serializable: ^3.2.5
  test: ^1.6.1
  mockito: ^4.1.1

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#000000"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/graphics/
    - assets/card_provider/
    - assets/graphics/drawer/

  fonts:
    - family: Heebo-Black
      fonts:
        - asset: fonts/Heebo-Black.ttf
    - family: Heebo-Thin
      fonts:
        - asset: fonts/Heebo-Thin.ttf
    - family: Heboo-Regular
      fonts:
        - asset: fonts/Heebo-Regular.ttf
flutter_intl:
  enabled: true
# 1.5.32
#  flutter packages pub run build_runner watch --delete-conflicting-outputs
#  rw.flipper
# flutter build appbundle  --build-number 1.5.32
# Db on device for debugging purpose: This PC\Pixel\Internal shared storage\Android\data\rw.flipper\files\database-development

