name: form_bloc

on:
  push:
    paths:
      - "packages/form_bloc/**"
      - ".github/workflows/form_bloc.yaml"

  pull_request:
    paths:
      - "packages/form_bloc/**"
      - ".github/workflows/form_bloc.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/form_bloc

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: dart test
