name: flipper_contacts
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^1.7.1
  stacked_hooks: 0.1.1+3
  stacked_services: ^0.5.4+2
  flutter_text_drawable: ^0.3.1
   # get it
  get_it: 
  injectable:
  cron: ^0.2.4
  contacts_service: ^0.4.6
  flipper_services:
    path: '../flipper_services'
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
