name: loading
description: A flutter widget of loading progress Indicator. Easy to use, easy to extend
version: 2.0.0

# author: ReiserXu <leonzone58@gmail.com>
homepage: https://github.com/leonzone/loading

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
