version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter channel
      - run: flutter doctor -v
      - run: flutter format -n --set-exit-if-changed ./lib ./test ./example
      - run: flutter test --coverage --coverage-path=lcov.info
      - run: bash <(curl -s https://codecov.io/bash)
