name: flipper_ui
description: >
  A new Flutter package project.
version: 1.0.3
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper_loading: ^2.0.0
  # flipper_models: ^0.0.1-dev.7
