name: flipper_ui
description: >
  A new Flutter package project.
version: 1.0.3
repository: https://github.com/yegobox/packages

environment:
  flutter: ">=3.22.0"
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flipper_loading: ^2.0.0
  overlay_support: ^2.1.0
  # adding this because I need constants from it,
  # maybe it is time to move all constants to its own package
  flipper_services: any
  easy_localization: ^3.0.7
  flipper_infra: any
  flowy_svg: any
  animations: ^2.0.11
  loading_indicator: ^3.1.0
  styled_widget: ^0.4.1
  
  
dependency_overrides:
  http: ^1.2.2
  meta: ^1.12.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^2.7.2
  device_info_plus: ^11.2.2
  
  
