include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: warning
    annotate_overrides: warning
    always_use_package_imports: warning

linter:
  rules:
    always_use_package_imports: true