name: flipper_routing
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^3.0.1
  flipper_chat:
  flipper_dashboard:
  flipper_login:
  flipper_models:
  stacked_services:
  flipper:
  flipper_finance:
  logger:
