name: flipper_routing
description: A new Flutter package project.
version: 0.0.1-dev.3
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.5.1
  flipper_dashboard: ^0.0.1-dev.5
  flipper_login: ^0.0.1-dev.5
  flipper_models: ^0.0.1-dev.7
  stacked_services: ^1.0.0
  stacked: ^3.1.0+2

  flipper_finance: ^0.0.1
  logger: ^1.1.0
  firebase_ui_auth: ^1.1.16
