name: flipper_routing
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^3.0.1
  flipper_chat: ^0.0.1
  flipper_dashboard: ^0.0.1
  flipper_login: ^0.0.1
  flipper_models: ^0.0.1
  stacked_services: ^0.8.16
  stacked: ^2.2.8
  flipper: ^99.99.99+99
  flipper_finance: ^0.0.1
  logger: ^1.1.0
