name: flipper
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/yegobox/packages
environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.0
  flipper_dashboard:
  flipper_ui: ^0.0.1
  flipper_models: ^0.0.1
  flipper_login: ^0.0.1
  flipper_services: ^0.0.1
  flipper_routing: ^0.0.1
  loading:
  overlay_support:
  flutter_screenutil:
  localize:
  universal_platform: ^1.0.0+1
  animations: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
