include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: ignore

linter:
  rules:
    # Disable because of FFI to non-Dart constants
    camel_case_types: false
    constant_identifier_names: false  
    non_constant_identifier_names: false