name: dart_console
description: A helper library for command-line applications that need more control over input/output than the standard library provides.

version: 1.1.0-pre.1
homepage: https://github.com/timsneath/dart_console

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ">=2.0.0 <3.0.0"
  win32: ^5.0.0
  intl: ^0.18.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
