name: flipper_loading
description: A flutter widget of flipper_loading progress Indicator. Easy to use, easy to extend
version: 2.0.0

homepage: https://github.com/leonzone/flipper_loading

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
dependency_overrides:
  http: ^1.2.2
  meta: ^1.11.0
  device_info_plus: ^11.2.2
  
  
  web: ^1.0.0
  
  json_annotation: ^4.9.0
  
