name: flipper_loading
description: A flutter widget of flipper_loading progress Indicator. Easy to use, easy to extend
version: 2.0.0

homepage: https://github.com/leonzone/flipper_loading

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
