name: reports
description: This package try to emitate the square point of sale report.
version: 0.0.1

homepage: "https://github.com/yegobox/flipper-mobile"

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.4
  customappbar: ^0.0.1
  flutter_date_pickers: ^0.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: rw.flipper.reports
        pluginClass: ReportsPlugin
      ios:
        pluginClass: ReportsPlugin
      macos:
        pluginClass: ReportsPlugin

    

