name: flipper_ui
description: A new Flutter package project.
version: 0.0.2

homepage: "https://yegobox.com"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  apptheme: ^0.0.1
  google_fonts: ^0.3.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:

