name: flipper_mocks
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flipper_models: any
  flipper_services: any
  realm: ^3.4.1
dependency_overrides:
  http: ^1.2.1
  meta: ^1.12.0
  
  sqlite3: ^2.4.6
  web: ^1.0.0
  aws_common: any
  json_annotation: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
