name: pos
description: A Keypad like square mobile app.
version: 0.1.4

homepage: 'https://github.com/yegobox/flipper-plugins/tree/pos-mobile'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

 
