name: flipper_chat
description: A new Flutter package project.
version: 0.0.1
# homepage:
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # line_icons: 2.0.1
  # animate_do: 2.0.0
  # bubble: 1.2.1
  #flipper:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
