mixin RRADEFAULTS {
  /// code for itemTyCd
  /// TODO: when singup choose wheter is a service
  /// or business so we know the type we need to set for itemTyCd when saving
  /// variant or item in rra world.
  static const String service = "3";
  static const String rawMaterial = "1";
  static const String finishedProduct = "2";
  static const List<String> packagingUnit = [
    "AM:1:Ampoule:Ampoule",
    "BA:2:Barrel:Barrel",
    "BC:3:Bottlecrate:Bottlecrate",
    "BE:4:Bundle:Bundle",
    "BF:5:Balloon, non-protected:Balloon, non-protected",
    "BG:6:Bag:Bag",
    "BJ:7:Bucket:Bucket",
    "BK:8:Basket:Basket",
    "BL:9:Bale:Bale",
    "BQ:10:Bottle, protected cylindrical:Bottle, protected cylindrical",
    "BR:11:Bar:Bar",
    "BV:12:Bottle, bulbous:Bottle, bulbous",
    "BZ:13:Bag:Bag",
    "CA:14:Can:Can",
    "CH:15:Chest:Chest",
    "CJ:16:Coffin:Coffin",
    "CL:17:Coil:Coil",
    "CR:18:Wooden Box, Wooden Case:Wooden Box, Wooden Case",
    "CS:19:Cassette:Cassette",
    "CT:20:Carton:Carton",
    "CTN:21:Container:Container",
    "CY:22:Cylinder:Cylinder",
    "DR:23:Drum:Drum",
    "GT:24:Extra Countable Item:Extra Countable Item",
    "HH:25:Hand Baggage:Hand Baggage",
    "IZ:26:Ingots:Ingots",
    "JR:27:Jar:Jar",
    "JU:28:Jug:Jug",
    "JY:29:Jerry CAN Cylindrical:Jerry CAN Cylindrical",
    "KZ:30:Canester:Canester",
    "LZ:31:Logs, in bundle/bunch/truss:Logs, in bundle/bunch/truss",
    "NT:32:Net:Net",
    "OU:33:Non-Exterior Packaging Unit:Non-Exterior Packaging Unit",
    "PD:34:Poddon:Poddon",
    "PG:35:Plate:Plate",
    "PI:36:Pipe:Pipe",
    "PO:37:Pilot:Pilot",
    "PU:38:Traypack:Traypack",
    "RL:39:Reel:Reel",
    "RO:40:Roll:Roll",
    "RZ:41:Rods, in bundle/bunch/truss:Rods, in bundle/bunch/truss",
    "SK:42:Skeletoncase:Skeletoncase",
    "TY:43:Tank, cylindrical:Tank, cylindrical",
    "VG:44:Bulk,gas(at 1031 mbar 15 oC):Bulk,gas(at 1031 mbar 15 oC)",
    "VL:45:Bulk,liquid(at normal temperature/pressure):Bulk,liquid(at normal temperature/pressure)",
    "VO:46:Bulk, solid, large particles(nodules):Bulk, solid, large particles(nodules)",
    "VQ:47:Bulk, gas (liquefied at abnormal temperature/pressure):Bulk, gas(liquefied at abnormal temperature/pressure)",
    "VR:48:Bulk, solid, granular particles(grains):Bulk, solid, granular particles(grains)",
    "VT:49:Extra Bulk Item:Extra Bulk Item",
    "VY:50:Bulk, fine particles(powder):Bulk, fine particles(powder)",
    "ML:51:Mills cigarette:Mills",
    "TN:52:TAN 1TAN REFER TO 20BAGS:TAN 1TAN REFER TO 20BAGS"
  ];
  static const List<String> unityOfQuantity = [
    "4B:1:Pair:Pair",
    "AV:2:Cap:Cap",
    "BA:3:Barrel:Barrel",
    "BE:4:Bundle:Bundle",
    "BG:5:Bag:Bag",
    "BL:6:Block:Block",
    "BLL:7:BLL Barrel:BLL Barrel (petroleum) (158,987 dm3)",
    "BX:8:Box:Box",
    "CA:9:Can:Can",
    "CEL:10:Cell:Cell",
    "CMT:11:centimetre:centimetre",
    "CR:12:CARAT:CARAT",
    "DR:13:Drum:Drum",
    "DZ:14:Dozen:Dozen",
    "GLL:15:Gallon:Gallon",
    "GRM:16:Gram:Gram",
    "GRO:17:Gross:Gross",
    "KG:18:Kilo-Gramme:Kilo-Gramme",
    "KTM:19:kilometre:kilometre",
    "KWT:20:kilowatt:kilowatt",
    "L:21:Litre:Litre",
    "LBR:22:pound:pound",
    "LK:23:link:link",
    "LTR:24:Litre:Litre",
    "M:25:Metre:Metre",
    "M2:26:Square Metre:Square Metre",
    "M3:27:Cubic Metre:Cubic Metre",
    "MGM:28:milligram:milligram",
    "MTR:29:metre:metre",
    "MWT:30:megawatt hour (1000 kW.h):megawatt hour (1000 kW.h)",
    "NO:31:Number:Number",
    "NX:32:part per thousand:part per thousand",
    "PA:33:packet:packet",
    "PG:34:plate:plate",
    "PR:35:pair:pair",
    "RL:36:reel:reel",
    "RO:37:roll:roll",
    "SET:38:set:set",
    "ST:39:sheet:sheet",
    "TNE:40:tonne (metric ton):tonne (metric ton)",
    "TU:41:tube:tube",
    "U:42:Pieces/item [Number]:Pieces/item [Number]",
    "YRD:43:yard:yard"
  ];
}
