version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8088:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: api
      POSTGRES_PASSWORD: NrVoyqD0SPqjHU0URCVWNz9tDV-nlg6C
    volumes:
      - api_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8087:6379'
    command: redis-server --requirepass EVAt68rSTHUDgqK_DBcwLQsJiZJOdYkV
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  api_data:

