name: Windows Store app
# https://medium.com/codechai/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd
on:
  push:
    branches: [mobile]
jobs:
  testing:
    name: Unit Testing
    # needs: [integrationTest]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@master
        with:
          # flutter-version: '1.22.3'
          channel: "stable"
      # pause test on server for now
      - run: git submodule update --init
      - run: flutter pub get
      - run: ./install.sh
      - run: flutter test
  windows:
    name: windowsInstaller
    needs: [testing]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@master
        with:
          flutter-version: "2.8.1"
          channel: "stable"
      - run: git submodule update --init
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: flutter pub run msix:create
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/runner/Release/flipper.msix"
          tag: v1.50.0.0
          token: ${{ secrets.GH_TOKEN }}
          # commit: ${{ github.sha }}
      - name: Upload  windows installer
        uses: actions/upload-artifact@v2
        with:
          name: winInstaller
          path: build/windows/runner/Release/flipper.msix
          # TODO: https://github.com/marketplace/actions/windows-store-publish use this to also publish to windows store.
  slackNotification:
    name: Slack Notification
    needs: [windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
# https://techcommunity.microsoft.com/t5/windows-dev-appconsult/enable-ci-cd-for-windows-apps-with-github-actions-and-azure/ba-p/1453991
# C:\Users\Sone\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\msix-2.1.3\lib\assets
# done.

# https://deveenrath.medium.com/flutter-pos-receipt-printing-ada7c1c7c33f
