name: Deploy MSIX to GitHub

on:
  release:
    types:
      - published

jobs:
  build-msix:
    name: Build MSIX
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@master
        with:
          flutter-version: "2.8.1"
          channel: "stable"
      - run: git submodule update --init
      - name: Configure Missing files
        run: |
          echo "$INDEX" >> web/index.html
          echo "$CONFIGDART" >> packages/flipper_login/lib/config.dart
          echo "$FIREBASEOPTIONS" >> lib/firebase_options.dart
        env:
          INDEX: ${{ secrets.INDEX }}
          CONFIGDART: ${{ secrets.CONFIGDART }}
          FIREBASEOPTIONS: ${{ secrets.FIREBASEOPTIONS }}
      - run: dart pub global activate melos 2.9.0
      - name: "Run Melos bootstrap"
        run: melos bootstrap
      - run: flutter config --enable-windows-desktop
      - run: flutter pub run msix:create
      - name: Upload MSIX to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: msix
          path: build/windows/runner/Release/flipper.msix

  deploy-msix:
    name: Deploy MSIX
    needs: [build-msix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Build Status
        run: |
          flutter build windows

          if [[ $? -eq 0 ]]; then
            echo "Build succeeded."
            echo "Uploading MSIX file to release."
            # Upload MSIX file to release here.
          else
            echo "Build failed."
            echo "Aborting action."
            exit 1
          fi
      - name: Check Environment Variables
        run: |
          echo "Checking environment variables."

          if [[ -z $INDEX ]]; then
            echo "Environment variable INDEX is not set."
            echo "Aborting action."
            exit 1
          fi

          if [[ -z $CONFIGDART ]]; then
            echo "Environment variable CONFIGDART is not set."
            echo "Aborting action."
            exit 1
          fi

          if [[ -z $FIREBASEOPTIONS ]]; then
            echo "Environment variable FIREBASEOPTIONS is not set."
            echo "Aborting action."
            exit 1
          fi

          echo "Environment variables are set."
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/runner/Release/flipper.msix"
          tag: v1.58.0.0
          token: ${{ secrets.GH_TOKEN }}
          # commit: ${{ github.sha }}
      - name: Upload winInstaller File
        uses: actions/upload-release-asset@v2
        with:
          asset_path: build/windows/runner/Release/winInstaller.exe
          asset_name: winInstaller.exe
          release: ${{ github.event.release.name }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
