name: Deploy the web
on:
  workflow_dispatch: # Enable manual run
  pull_request: #TODO:remove
  push:
    branches: [mobile]
    # Sequence of patterns matched against refs/tags
    # tags:
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy-web:
    runs-on: ubuntu-18.04
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@master
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Install web dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install -g firebase-tools

      # Checkout flipper code and get packages.
      - name: Checkout flipper code
        uses: actions/checkout@v2
      - name: submodule init
        run: git submodule update --init
      - run: flutter pub get

      - run: flutter build  web --release

      - run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
