name: flipper_actionable
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"


dependencies:
  intl: ^0.19.0
  injectable: ^2.5.0
  get_it: ^7.7.0
  stacked: ^3.4.3
  flipper_services: any
  meta: ^1.12.0
dependency_overrides:
  http: ^1.2.2
  meta: ^1.12.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^2.7.2
  device_info_plus: ^11.2.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.6.0
  build_runner: ^2.4.14
