name: flipper_actionable
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"


dependencies:
  intl: ^0.20.2
  injectable: ^2.5.0
  get_it: ^8.0.3
  stacked: ^3.4.3
  flipper_services: any
  meta: ^1.12.0
dependency_overrides:
  http: ^1.2.2
  meta: ^1.12.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^2.9.0
  device_info_plus: ^11.3.3
  archive: ^3.6.1
  excel: ^4.0.6
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.6.0
  build_runner: ^2.4.15
